[package]
name = "langchain-test"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
langchain-rust = { version = "4.6.0", features = ["postgres"] }
serde_json = "1.0.138"
tokio = "1.43.0"
